project_id = "xmuiapxfpgqvuyzqngug"

[functions.ai-assistant]
verify_jwt = false

[functions.news-api]
verify_jwt = false

[functions.news-search]
verify_jwt = false

[functions.stock-api]
verify_jwt = false

[functions.weather-api]
verify_jwt = false

[functions.search]
verify_jwt = false
