// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rijldvcoabidmdmenyic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpamxkdmNvYWJpZG1kbWVueWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTUxMjgsImV4cCI6MjA2MTM3MTEyOH0.c03_DrvJj98tvBh1o5qO0VWCDUifpXhsxijhO3zORPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);